# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  python_min: 3.10.0
  name: django-breeze
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_breeze-${{ version }}.tar.gz
  sha256: e0ba4245e7e16521b3e726f2823d6fef6eeb88ccb03eb22949112b7a420ce535

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - django-breeze = django_breeze.scripts.django_breeze:run

requirements:
  host:
    - python 3.10.0.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0.0
    - django-vite ==3.0.5
    - inertia-django ==0.6.0

tests:
  - python:
      imports:
        - django_breeze
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - django-breeze --help

about:
  summary: Django Breeze provides a minimal and simple starting point for building a Django application with Inertia and Vite with minimal or no configuration. Styled with Tailwind CSS.
  license: MIT
  license_file: LICENSE.md
  homepage: https://github.com/Louxsdon/django-breeze

extra:
  recipe-maintainers:
    - rxm7706
